name: cicd-workflow to create docker image and upload into Dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node-version: [18.x, 20.x]
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: npm install and build
      #   run: |
      #     npm install
      #     npm run build
      #   env:
      #     CI: true
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker Image
        env: 
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/task05062025:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/task05062025:${IMAGE_TAG}
      - name: ssh-docker
          # You may pin to the exact commit or the version.
          # uses: prvious/ssh-docker@de19b5d90879d262b04fc8a34b8aa69f71c8178e
        uses: prvious/ssh-docker@v1
        with:
            # Docker host to connect to
          remote_host: ssh://${{ secrets.SSH_USERNAME }}
            # SSH public key of the server
          ssh_public_key: ${{ secrets.PUBLIC_KEY }}
            # SSH private key to use to connect
          ssh_private_key: ${{ secrets.MY_SECRET }}
        
